# baseURL = "https://example.com"
languageCode = "en-us"
title = "essn"
copyright = "© essn"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
mode = "auto"
useCDN = false
subtitle = "I make things. Sometimes, they're interesting. *Note: This site is WIP and I am adding more content as time allows :)*"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/essn/essn"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jesse-pledger-29946aa4/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
